fix: remove redundant DART_API from member functions
When a class has DART_API (dllexport), member functions inherit the
export attribute. Having DART_API on both class and member causes
MSVC error C2487: 'member of dll interface class may not be declared
with dll interface'.